# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jan/Documents/Research/Projects/Fotokite/Code/fotokite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jan/Documents/Research/Projects/Fotokite/Code/fotokite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jan/Documents/Research/Projects/Fotokite/Code/fotokite/CMakeFiles /Users/jan/Documents/Research/Projects/Fotokite/Code/fotokite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jan/Documents/Research/Projects/Fotokite/Code/fotokite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fotokite

# Build rule for target.
Fotokite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fotokite
.PHONY : Fotokite

# fast build rule for target.
Fotokite/fast:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/build
.PHONY : Fotokite/fast

Communication.o: Communication.cpp.o

.PHONY : Communication.o

# target to build an object file
Communication.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Communication.cpp.o
.PHONY : Communication.cpp.o

Communication.i: Communication.cpp.i

.PHONY : Communication.i

# target to preprocess a source file
Communication.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Communication.cpp.i
.PHONY : Communication.cpp.i

Communication.s: Communication.cpp.s

.PHONY : Communication.s

# target to generate assembly for a file
Communication.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Communication.cpp.s
.PHONY : Communication.cpp.s

DataLog.o: DataLog.cpp.o

.PHONY : DataLog.o

# target to build an object file
DataLog.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/DataLog.cpp.o
.PHONY : DataLog.cpp.o

DataLog.i: DataLog.cpp.i

.PHONY : DataLog.i

# target to preprocess a source file
DataLog.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/DataLog.cpp.i
.PHONY : DataLog.cpp.i

DataLog.s: DataLog.cpp.s

.PHONY : DataLog.s

# target to generate assembly for a file
DataLog.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/DataLog.cpp.s
.PHONY : DataLog.cpp.s

Fotokite.o: Fotokite.cpp.o

.PHONY : Fotokite.o

# target to build an object file
Fotokite.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Fotokite.cpp.o
.PHONY : Fotokite.cpp.o

Fotokite.i: Fotokite.cpp.i

.PHONY : Fotokite.i

# target to preprocess a source file
Fotokite.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Fotokite.cpp.i
.PHONY : Fotokite.cpp.i

Fotokite.s: Fotokite.cpp.s

.PHONY : Fotokite.s

# target to generate assembly for a file
Fotokite.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Fotokite.cpp.s
.PHONY : Fotokite.cpp.s

FotokiteState.o: FotokiteState.cpp.o

.PHONY : FotokiteState.o

# target to build an object file
FotokiteState.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/FotokiteState.cpp.o
.PHONY : FotokiteState.cpp.o

FotokiteState.i: FotokiteState.cpp.i

.PHONY : FotokiteState.i

# target to preprocess a source file
FotokiteState.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/FotokiteState.cpp.i
.PHONY : FotokiteState.cpp.i

FotokiteState.s: FotokiteState.cpp.s

.PHONY : FotokiteState.s

# target to generate assembly for a file
FotokiteState.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/FotokiteState.cpp.s
.PHONY : FotokiteState.cpp.s

Serial.o: Serial.cpp.o

.PHONY : Serial.o

# target to build an object file
Serial.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Serial.cpp.o
.PHONY : Serial.cpp.o

Serial.i: Serial.cpp.i

.PHONY : Serial.i

# target to preprocess a source file
Serial.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Serial.cpp.i
.PHONY : Serial.cpp.i

Serial.s: Serial.cpp.s

.PHONY : Serial.s

# target to generate assembly for a file
Serial.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/Serial.cpp.s
.PHONY : Serial.cpp.s

SerialCommunication.o: SerialCommunication.cpp.o

.PHONY : SerialCommunication.o

# target to build an object file
SerialCommunication.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SerialCommunication.cpp.o
.PHONY : SerialCommunication.cpp.o

SerialCommunication.i: SerialCommunication.cpp.i

.PHONY : SerialCommunication.i

# target to preprocess a source file
SerialCommunication.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SerialCommunication.cpp.i
.PHONY : SerialCommunication.cpp.i

SerialCommunication.s: SerialCommunication.cpp.s

.PHONY : SerialCommunication.s

# target to generate assembly for a file
SerialCommunication.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SerialCommunication.cpp.s
.PHONY : SerialCommunication.cpp.s

SocketCommunication.o: SocketCommunication.cpp.o

.PHONY : SocketCommunication.o

# target to build an object file
SocketCommunication.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SocketCommunication.cpp.o
.PHONY : SocketCommunication.cpp.o

SocketCommunication.i: SocketCommunication.cpp.i

.PHONY : SocketCommunication.i

# target to preprocess a source file
SocketCommunication.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SocketCommunication.cpp.i
.PHONY : SocketCommunication.cpp.i

SocketCommunication.s: SocketCommunication.cpp.s

.PHONY : SocketCommunication.s

# target to generate assembly for a file
SocketCommunication.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/SocketCommunication.cpp.s
.PHONY : SocketCommunication.cpp.s

VisualPoseEstimator.o: VisualPoseEstimator.cpp.o

.PHONY : VisualPoseEstimator.o

# target to build an object file
VisualPoseEstimator.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/VisualPoseEstimator.cpp.o
.PHONY : VisualPoseEstimator.cpp.o

VisualPoseEstimator.i: VisualPoseEstimator.cpp.i

.PHONY : VisualPoseEstimator.i

# target to preprocess a source file
VisualPoseEstimator.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/VisualPoseEstimator.cpp.i
.PHONY : VisualPoseEstimator.cpp.i

VisualPoseEstimator.s: VisualPoseEstimator.cpp.s

.PHONY : VisualPoseEstimator.s

# target to generate assembly for a file
VisualPoseEstimator.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/VisualPoseEstimator.cpp.s
.PHONY : VisualPoseEstimator.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Fotokite.dir/build.make CMakeFiles/Fotokite.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Fotokite"
	@echo "... Communication.o"
	@echo "... Communication.i"
	@echo "... Communication.s"
	@echo "... DataLog.o"
	@echo "... DataLog.i"
	@echo "... DataLog.s"
	@echo "... Fotokite.o"
	@echo "... Fotokite.i"
	@echo "... Fotokite.s"
	@echo "... FotokiteState.o"
	@echo "... FotokiteState.i"
	@echo "... FotokiteState.s"
	@echo "... Serial.o"
	@echo "... Serial.i"
	@echo "... Serial.s"
	@echo "... SerialCommunication.o"
	@echo "... SerialCommunication.i"
	@echo "... SerialCommunication.s"
	@echo "... SocketCommunication.o"
	@echo "... SocketCommunication.i"
	@echo "... SocketCommunication.s"
	@echo "... VisualPoseEstimator.o"
	@echo "... VisualPoseEstimator.i"
	@echo "... VisualPoseEstimator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

